### ISSUE TITLE
BUG提交

### ISSUE THREAD

**Issue by reinershir** [ushelp/EasyEE-Auto#2]
1、生成的页面中 搜索、清除按钮未用国际化,无查询条件时依旧有按钮
2、生成的页面中国际化lable.chkbox  应该是label.chkbox ，所有生成页面不是默认的页面的代码都是label打成了lable

3、生成非默认页面类型报错，浏览器：Uncaught TypeError: Cannot read property 'length' of undefined
 控制台：If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??

4、生成的sqlmap get方法多了个where

5、控制器get方法是Serializable 类型怎么传？（这个不算BUG，我直接用AJAX传会报错）

6、Action的get方法居然放了super.setMsgKey("msg.updateSuccess")代码，结果就是查询GET方法时会弹出提示框

7、手动加上sqlmap关联查询后报无法序列化错误，一看是因为使用了懒加载 

以下是建议：
1、表随实体类一起生成
2、生成的代码不支持排序
3、自动生成的页面没有加上权限判断
4、直接修改生成代码的源码比较麻烦，建议开放一个读取模板生成代码的接口。

**Comment by reinershir** [comment]
使用的项目是SM-SPRINGBOOT

**Comment by ushelp** [comment]
感谢你的反馈，新的 Release 3.1.2 和 部分更新的 4.2.0-RELEASE_fixed.2。

1. 按钮已应用国际化和修复问题。
请更新国际化文件，添加

messages_en.properties, messages.properties
```Properties
label.clear      = Clear
label.search     = Search
```

messages_zh_CN.properties
```Properties
label.clear      = 清除
label.search     = 搜索
```

页面按钮使用响应国际化标签。

Struts
```HTML
<s:text name="label.search"></s:text>
<s:text name="label.clear"></s:text>
```

SpringMVC
```HTML
<s:message code="label.search"></s:message>
<s:message code="label.clear"></s:message>
```

2. 已修复

3. 未能重现，可以提供更多信息，或查看是否是哪些配置不规范引起的

4. 已修复

5. Serializable 一般可以正常接收各种基本数据类型和String。如果不行，可以手动设置为您的 ID 具体类型。

6. 已修复

7.  延迟加载策略根据需求可以在 `mybatis-config.xml` 中关闭

其他：
1、表随实体类一起生成； 
作为 TODO

2、生成的代码不支持排序； 
用户管理部分排序需要更新最新的 `SysUserServiceImpl.java` 文件。自动生成代码测试是支持的。

3、自动生成的页面没有加上权限判断；
页面默认在 Shiro 的 perms URL 权限过滤器控制中，具有权限才可访问，无需加入权限代码。

4、直接修改生成代码的源码比较麻烦，建议开放一个读取模板生成代码的接口。 
源码已经发布，欢迎 PR

项目源码已经发布到 GitHub，欢迎您的 PR。
