### ISSUE TITLE
配置权限是哪个文件？

### ISSUE THREAD

**Issue by lmdiloveu** [ushelp/EasyEE-Auto#3]
或者在哪里配置？

**Comment by ushelp** [comment]
@lmdiloveu 在生成完代码之后，会输出需要配置的菜单权限和动作权限 web url 地址，登录系统在后台添加需要的菜单权限和动作权限，然后按需分配即可。

EasyEE 使用的 Shiro 作为安全框架，如果需要进一步控制非 web url 地址权限，可以修改 `spring_shiro.xml`。
