### ISSUE TITLE
点击修改按钮无法弹出修改界面

### ISSUE THREAD

**Issue by lirenhao** [ushelp/EasyEE-Auto#4]
生成的SH代码，点击页面的修改按钮后，JS部分判断是否有选中时，获取的是row但判断的却是rows，是Bug还是我的用法有问题？（生成后代码没有做修改）

**Comment by ushelp** [comment]
感谢反馈，是一个 BUG。
@lirenhao

**Comment by ushelp** [comment]
@lirenhao Bug 已在 1.3.3 版本修复，并发布到中央仓库。但 Maven 中央仓库同步需要时间，临时可以直接下载最新的 jar 包。

**Comment by lirenhao** [comment]
@ushelp 很高兴你们能处理我的问题，谢谢！
